version: "3.9"

services:
    mysql:
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: password
      volumes:
          - ./storage/app/mysql:/var/lib/mysql

    database:
      image: mysql:latest
      MYSQL_ROOT_PASSWORD: password
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
      ports:
          - 3306:3306
      volumes:

    redis:
      image: redis:latest
      restart: always
      ports:
          - "6379:6379"

    php:
      build:
          context: ./
          dockerfile: ./docker/php/Dockerfile
      ports:
          - 86:80
      restart: always

    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        ports:
        - 86:80
        restart: always
        depends_on:
            - php

